services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bit_forum
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
  
  rabbitmq:
   image: rabbitmq:3-management
   ports:
      - "5672:5672"
      - "15672:15672"
  
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on: 
      - mysql
      - redis
      - rabbitmq
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/bit_forum?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=UTF-8
      SPRING_DATA_REDIS_HOST: redis
      SPRING_RABBITMQ_HOST: rabbitmq

volumes:
  mysql-data: